baseURL: "https://www.anbeda.ch"
#baseURL: "https://anbeda-web.e1608f7.deploio.app/"
languageCode: "de_CH"
title: "anbeda AG - rund um Solar"
paginate: 5
theme: "PaperMod"
defaultContentLanguage: "de"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# todo
# - img click -> full version
# - favicon

taxonomies:
  tag: tags

permalinks:
  posts: '/posts/:title/'

params:
  env: production
  title: "anbeda.ch - Solar"
  defaultTheme: auto # to switch between dark or light according to browser theme
  DateFormat: "2. January 2006"
  ShowRssButtonInSectionTermList: true

  homeInfoParams:
    Title: Willkommen auf dem Solar Blog von anbeda AG
    Content: Photovoltaik ist mein Hobby (Hauptjob ist [Nine](https://nine.ch)) und
      ich möchte möglichst viele mit dem Solarvirus infizieren! Die anbeda AG dient dazu, um
      alles zu tun, was man als Einzelperson nicht darf - z.B. Solarpanels vom Grosshändler
      kaufen! Gerne unterstütze ich euch beim \#Selbstbau mit planen, Material oder Tipps! 
      Folge mir auf [Twitter](https://twitter.com/tomdawon)!

  socialIcons:
    - name: "twitter"
      url: "https://twitter.com/tomdawon"
    - name: "github"
      url: "https://github.com/thomhug"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/thomas-hug/"
    - name: "rss"
      url: "/index.xml"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  editPost:
    URL: "https://github.com/thomhug/anbeda-web/blob/main/content"
    Text: "Änderungen vorschlagen" # edit text
    appendFilePath: true # to append file path to Edit link

module:
  mounts:
    - source: layouts
      target: layouts
    - source: blog
      target: content/posts
    - source: docs
      target: content/docs
    - source: images
      target: assets/images  

menu:
  main:
#    - identifier: categories
#      name: categories
#      url: /categories/
#      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
#    - identifier: example
#      name: example.org
#      url: https://example.org
#      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  asciidocExt:
    attributes: {}
    backend: html5
    extensions: []
    failureLevel: fatal
    noHeaderOrFooter: true
    preserveTOC: false
    safeMode: unsafe
    sectionNumbers: false
    trace: false
    verbose: false
    workingFolderCurrent: false
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer:
        apostrophe: '&rsquo;'
        disable: false
        ellipsis: '&hellip;'
        emDash: '&mdash;'
        enDash: '&ndash;'
        leftAngleQuote: '&laquo;'
        leftDoubleQuote: '&ldquo;'
        leftSingleQuote: '&lsquo;'
        rightAngleQuote: '&raquo;'
        rightDoubleQuote: '&rdquo;'
        rightSingleQuote: '&rsquo;'
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2

outputs:
  home:
    - HTML
    - RSS
    - JSON

